version: '3.1'
services:
    mongo:
        image: mongo:latest
        environment:
            - MONGO_INITDB_DATABASE=budget
            - MONGO_INITDB_USER=budget_user
            - MONGO_INITDB_PASSWORD=budget_pass
        volumes:
            - ./data/mongo:/data/db
        ports:
            - '27017-27019:27017-27019'